// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1

import (
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	reflect "reflect"
)

// Deprecated: GetGeneratedDeepCopyFuncs returns the generated funcs, since we aren't registering them.
func GetGeneratedDeepCopyFuncs() []conversion.GeneratedDeepCopyFunc {
	return []conversion.GeneratedDeepCopyFunc{
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*AstaXie).DeepCopyInto(out.(*AstaXie))
			return nil
		}, InType: reflect.TypeOf(&AstaXie{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*AstaXieList).DeepCopyInto(out.(*AstaXieList))
			return nil
		}, InType: reflect.TypeOf(&AstaXieList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*AstaXieSpec).DeepCopyInto(out.(*AstaXieSpec))
			return nil
		}, InType: reflect.TypeOf(&AstaXieSpec{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*AstaXieStatus).DeepCopyInto(out.(*AstaXieStatus))
			return nil
		}, InType: reflect.TypeOf(&AstaXieStatus{})},
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AstaXie) DeepCopyInto(out *AstaXie) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new AstaXie.
func (x *AstaXie) DeepCopy() *AstaXie {
	if x == nil {
		return nil
	}
	out := new(AstaXie)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (x *AstaXie) DeepCopyObject() runtime.Object {
	if c := x.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AstaXieList) DeepCopyInto(out *AstaXieList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AstaXie, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new AstaXieList.
func (x *AstaXieList) DeepCopy() *AstaXieList {
	if x == nil {
		return nil
	}
	out := new(AstaXieList)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (x *AstaXieList) DeepCopyObject() runtime.Object {
	if c := x.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AstaXieSpec) DeepCopyInto(out *AstaXieSpec) {
	*out = *in
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new AstaXieSpec.
func (x *AstaXieSpec) DeepCopy() *AstaXieSpec {
	if x == nil {
		return nil
	}
	out := new(AstaXieSpec)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AstaXieStatus) DeepCopyInto(out *AstaXieStatus) {
	*out = *in
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new AstaXieStatus.
func (x *AstaXieStatus) DeepCopy() *AstaXieStatus {
	if x == nil {
		return nil
	}
	out := new(AstaXieStatus)
	x.DeepCopyInto(out)
	return out
}
